service:
  name: alexa-skill-thermometer

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  memorySize: 128 # min
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess

custom:
  webpack:
    packager: yarn

functions:
  AlexaSkill:
    handler: handler.handler
    events:
      - alexaSkill: alexa-appkit.amazon.com # unspecified
    environment:
      TZ: Asia/Tokyo
